### ISSUE TITLE
Please rename the repository

### ISSUE THREAD

**Issue by codingus-g** [talecrafter/AnimationImporter#46]
"PixelAnimationImporter" or "AcespriteAnimationImporter" are good names reflecting the specifics of this project.
Just "AnimationImporter" will always imply first and foremost import of animated skeletal meshes, in the unity context.

**Comment by talecrafter** [comment]
I would agree that the project could have a better defined name.

Finding the correct one without grabbing a fantasy name proves to be difficult, though.
Since it supports both Aseprite and PyxelEdit, a name connected to either one would not fit.
Some form of Pixelart is not 100% correct, since even Aseprite doesn't define itself as a pure pixelart tool and could be used as a general sprite tool.
I don't agree that AnimationImporter will imply animated skeletal meshes. Unity supports a lot of animation import by default, so any external tool would imply a special use case anyway.

Maybe we'll find a better name in the future. Maybe not.
